import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { Providers } from "@/Providers/Provider";
import AuthWrapper from "@/Providers/AuthWrapper";
// import { CallPopup } from "@/components/CallPopup";

const montserrat = Montserrat({
    subsets: ["latin"],
    variable: "--font-montserrat",
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${montserrat.variable} font-m-400 antialiased`}>
                <Providers>
                    <AuthWrapper>
                        {children}
                        <Toaster />
                        {/* <CallPopup></CallPopup> */}
                    </AuthWrapper>
                </Providers>
            </body>
        </html>
    );
}
